[influxdb]
url = "http://localhost:8086"
database = "gnettrack"
username = ""
password = ""
# InfluxDB 2.x configuration (recommended)
org = "my-org"
token = "my-super-secret-auth-token"
# InfluxDB 1.x configuration (legacy) - set org and token to "" to use 1.x mode
# username = "your_username"
# password = "your_password"

[logging]
level = "info"

[processing]
# Batch size for processing records
batch_size = 1000
# Skip invalid records instead of failing
skip_invalid = true